### ISSUE TITLE
Error during Get-AGMLibFollowJobStatus 

### ISSUE THREAD

**Issue by matt63** [Actifio/AGMPowerLib#10]
Running this command on a running job:
Get-AGMLibFollowJobStatus Job_28139997

I get these errors, but execution continues.

InvalidArgument: /Users/mferrari/.local/share/powershell/Modules/AGMPowerCLI/0.0.0.17/AGMPowerCLICommonFunctions.ps1:746
Line |
 746 |      $convertedtime =  [timespan]::fromseconds($duration/1000000)
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert value "00:20:40" to type "System.Int32". Error: "Input string was not in a correct
     | format."

InvalidOperation: /Users/mferrari/.local/share/powershell/Modules/AGMPowerCLI/0.0.0.17/AGMPowerCLICommonFunctions.ps1:753
Line |
 753 |      $totalhours + $convertedtime.ToString("\:mm\:ss")
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

jobname      status  progress queuedate           startdate           duration
-------      ------  -------- ---------           ---------           --------
Job_28139997 running       75 2020-10-16 16:03:02 2020-10-16 16:03:08

**Comment by aussiestorblog** [comment]
Thanks for reporting this.   This resulted from adding duration conversion to job, job status and job history API calls in AGMPowerCLI.        So when AGMPowerLib functions tried to convert duration, instead of a number, it was getting an actual duration.   I have fixed the two affected reports. in AGMPowerLib 0.0.0.22 so please upgrade to that version.

 ## [0.0.0.22] 2020-10-17
        AGMPowerCLI 0.0.0.17 added duration conversion, which clashed with functions already using Convert-AGMDuration to do this.   Corrected Get-AGMLibRunningJobs,Get-AGMLibFollowJobStatus.
